name: Update File

on:
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update File
      run: |
        echo "Contenu à écrire dans le fichier" > data/data.txt
        git config --global user.email "2zbgnk@gmail.com"
        git config --global user.name "LaMaCourses"
        git add data/data.txt
        git commit -m "Mise à jour du fichier"

        git push https://LaMaCourses:LABADENQUET2_SECRET@github.com/LaMaCourses/Labadenquet     
      env:
        GITHUB_TOKEN: ${{ secrets.LABADENQUET2_SECRET }}
